version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=Password@123"
      - "MYSQL_DATABASE=golang"   
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DB_USER=user
      - DB_PASSWORD=Password@123
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=golang
      - SERVER_PORT=8080
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"